"""empty message

Revision ID: 56e5df1ce8b3
Revises: 
Create Date: 2024-08-21 16:50:05.694420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e5df1ce8b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('hscodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('taxtables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_duty', sa.Integer(), nullable=True),
    sa.Column('excise_duty', sa.Integer(), nullable=True),
    sa.Column('export_duty', sa.Integer(), nullable=True),
    sa.Column('import_vat', sa.Integer(), nullable=True),
    sa.Column('import_declaration_fee', sa.Integer(), nullable=True),
    sa.Column('railway_development_levy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hscodes.id'], name=op.f('fk_products_hs_code_id_hscodes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exporttables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fob_value', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('export_date', sa.DateTime(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('hscode_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['countries.id'], name=op.f('fk_exporttables_destination_id_countries')),
    sa.ForeignKeyConstraint(['hscode_id'], ['hscodes.id'], name=op.f('fk_exporttables_hscode_id_hscodes')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_exporttables_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importtables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.String(), nullable=True),
    sa.Column('entry_number', sa.Integer(), nullable=True),
    sa.Column('entry_status', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('discharge_port', sa.String(), nullable=True),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('hscode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['countries.id'], name=op.f('fk_importtables_destination_id_countries')),
    sa.ForeignKeyConstraint(['hscode_id'], ['hscodes.id'], name=op.f('fk_importtables_hscode_id_hscodes')),
    sa.ForeignKeyConstraint(['origin_id'], ['countries.id'], name=op.f('fk_importtables_origin_id_countries')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_importtables_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('importtables')
    op.drop_table('exporttables')
    op.drop_table('products')
    op.drop_table('user')
    op.drop_table('taxtables')
    op.drop_table('hscodes')
    op.drop_table('countries')
    # ### end Alembic commands ###
