"""empty message

Revision ID: 969e92efb38c
Revises: 9ab766f457b2
Create Date: 2024-08-20 17:37:07.803431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969e92efb38c'
down_revision = '9ab766f457b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exportbtables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fob_value', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('export_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importtables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=True),
    sa.Column('entry_number', sa.Integer(), nullable=True),
    sa.Column('entry_status', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('discharge_port', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxtables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_duty', sa.Integer(), nullable=True),
    sa.Column('excise_duty', sa.Integer(), nullable=True),
    sa.Column('export_duty', sa.Integer(), nullable=True),
    sa.Column('export_rate', sa.Integer(), nullable=True),
    sa.Column('import_declaration_fee', sa.Integer(), nullable=True),
    sa.Column('railway_development_levy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxtables')
    op.drop_table('importtables')
    op.drop_table('exportbtables')
    # ### end Alembic commands ###
